# Generated by Django 3.2.6 on 2021-08-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snacks',
            old_name='reviewer',
            new_name='purchaser',
        ),
        migrations.RemoveField(
            model_name='snacks',
            name='rating',
        ),
        migrations.AddField(
            model_name='snacks',
            name='description',
            field=models.TextField(default=0, max_length=256),
        ),
    ]
